# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:  #yaani jab bhe koi yeh push pull hou tou workflow will run here
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: #tells what the workflow will do
  build: #build means code will run and be tested as well, agar sirf test karna tou build ke jagah khaali test likh dogay

    runs-on: ubuntu-latest #will run on cloud islye doesnt matter if u have ubantu or not

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x] #idhar 3 workflow chalay ga, 1 each for these 3 versions
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci #idhar dependencies installed horhi
    - run: npm run build --if-present #agar upar build nai, sirf test tou dont need this command warna error
    - run: npm test
